use anyhow::{ensure, Result};

pub(super) fn validate(args: &[String]) -> Result<()> {
    let command = args.first().map(String::as_str).unwrap_or("");
    let extra: &[&str] = match command {
        "status" => &[
            "-s",
            "--short",
            "-b",
            "--branch",
            "--porcelain",
            "--ignored",
            "--untracked-files",
            "--ahead-behind",
            "--no-ahead-behind",
            "--renames",
            "--no-renames",
        ],
        "diff" => &[
            "--cached",
            "--staged",
            "--check",
            "--exit-code",
            "--quiet",
            "--diff-filter",
        ],
        "show" | "log" => &[
            "--oneline",
            "--graph",
            "--all",
            "--branches",
            "--tags",
            "--remotes",
            "--decorate",
            "--no-decorate",
            "--reverse",
            "--first-parent",
            "--no-merges",
            "--merges",
            "--follow",
            "--parents",
            "--date-order",
            "--topo-order",
            "--max-count",
            "-n",
            "--skip",
            "--since",
            "--until",
            "--after",
            "--before",
            "--author",
            "--committer",
            "--grep",
            "--format",
            "--pretty",
            "--date",
            "--encoding",
            "--no-notes",
            "--notes",
        ],
        "ls-files" => &[
            "--cached",
            "-c",
            "--deleted",
            "-d",
            "--modified",
            "-m",
            "--others",
            "-o",
            "--ignored",
            "-i",
            "--stage",
            "-s",
            "--unmerged",
            "-u",
            "--killed",
            "-k",
            "--directory",
            "--no-empty-directory",
            "--deduplicate",
            "--eol",
            "--full-name",
            "--error-unmatch",
            "--exclude",
            "--exclude-from",
            "--exclude-standard",
            "--exclude-per-directory",
            "-z",
        ],
        "ls-tree" => &[
            "-d",
            "-r",
            "-t",
            "-l",
            "--name-only",
            "--name-status",
            "--full-name",
            "--full-tree",
            "-z",
            "--abbrev",
        ],
        "rev-parse" => &[
            "--verify",
            "--quiet",
            "-q",
            "--short",
            "--show-toplevel",
            "--show-prefix",
            "--show-cdup",
            "--is-inside-work-tree",
            "--is-bare-repository",
            "--git-dir",
            "--absolute-git-dir",
            "--git-common-dir",
            "--show-object-format",
            "--symbolic",
            "--symbolic-full-name",
            "--abbrev-ref",
            "--revs-only",
            "--no-revs",
            "--flags",
            "--no-flags",
            "--end-of-options",
        ],
        "rev-list" => &[
            "--all",
            "--count",
            "--objects",
            "--object-names",
            "--no-object-names",
            "--left-right",
            "--cherry-pick",
            "--boundary",
            "--first-parent",
            "--no-merges",
            "--merges",
            "--max-count",
            "-n",
            "--skip",
            "--max-parents",
            "--min-parents",
            "--since",
            "--until",
            "--reverse",
            "--date-order",
            "--topo-order",
            "--parents",
        ],
        "describe" => &[
            "--tags",
            "--all",
            "--always",
            "--long",
            "--exact-match",
            "--abbrev",
            "--match",
            "--exclude",
            "--dirty",
            "--broken",
            "--contains",
            "--first-parent",
        ],
        "grep" => &[
            "-n",
            "--line-number",
            "--column",
            "-i",
            "--ignore-case",
            "-w",
            "--word-regexp",
            "-v",
            "--invert-match",
            "-l",
            "--files-with-matches",
            "-L",
            "--files-without-match",
            "-h",
            "--no-filename",
            "-H",
            "--with-filename",
            "-c",
            "--count",
            "-q",
            "--quiet",
            "-z",
            "--null",
            "-a",
            "--text",
            "-I",
            "-E",
            "-G",
            "-P",
            "-F",
            "--cached",
            "--untracked",
            "--no-exclude-standard",
            "--exclude-standard",
            "--all-match",
            "-e",
            "--regexp",
            "-f",
            "--file",
            "-A",
            "-B",
            "-C",
            "--after-context",
            "--before-context",
            "--context",
            "-m",
            "--max-count",
            "--threads",
            "--max-depth",
            "--no-textconv",
            "--no-color",
            "--color",
        ],
        _ => anyhow::bail!("only read-only git subcommands are allowed"),
    };
    let diff_options = [
        "--stat",
        "--numstat",
        "--shortstat",
        "--name-only",
        "--name-status",
        "--raw",
        "--patch",
        "-p",
        "--no-patch",
        "-s",
        "--binary",
        "--summary",
        "--no-color",
        "--color",
        "--no-renames",
        "--find-renames",
        "-M",
        "--find-copies",
        "-C",
        "--relative",
        "--full-index",
        "--abbrev",
        "--no-prefix",
        "--src-prefix",
        "--dst-prefix",
        "--word-diff",
        "--word-diff-regex",
        "--unified",
        "-U",
        "-w",
        "--ignore-all-space",
        "--ignore-space-change",
        "-b",
        "--ignore-space-at-eol",
        "--ignore-blank-lines",
        "--no-ext-diff",
        "--no-textconv",
    ];
    let tail: Vec<_> = args
        .iter()
        .skip(1)
        .take_while(|arg| arg.as_str() != "--")
        .collect();
    for (index, arg) in tail.iter().enumerate() {
        if arg.starts_with('-') && arg.as_str() != "-" {
            let option = arg.split('=').next().unwrap();
            let numbered = ["-n", "-U", "-A", "-B", "-C", "-m"].iter().any(|flag| {
                extra.contains(flag) || (matches!(command, "diff" | "show" | "log") && diff_options.contains(flag))
            } && arg.strip_prefix(flag).is_some_and(|n| !n.is_empty() && n.bytes().all(|b| b.is_ascii_digit())));
            ensure!(
                extra.contains(&option)
                    || numbered
                    || (matches!(command, "diff" | "show" | "log")
                        && diff_options.contains(&option)),
                "git option is not confirmed read-only: {option}"
            );
            if matches!(option, "--pretty" | "--format") {
                let value = arg
                    .split_once('=')
                    .map(|(_, value)| value)
                    .or_else(|| tail.get(index + 1).map(|s| s.as_str()))
                    .unwrap_or("medium");
                ensure!(
                    !value.contains("%G")
                        && ([
                            "oneline",
                            "short",
                            "medium",
                            "full",
                            "fuller",
                            "reference",
                            "raw",
                            "email"
                        ]
                        .contains(&value)
                            || value.starts_with("format:")
                            || value.starts_with("tformat:")
                            || value.contains('%')),
                    "custom git pretty aliases and signature formats are blocked"
                );
            }
        }
    }
    Ok(())
}
