[package]
name = "opencoder-dag"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
chrono.workspace = true
opencoder-dag-binary.workspace = true

[dev-dependencies]
tempfile.workspace = true
