- job_name: opencoder-scheduler
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  authorization:
    type: Bearer
    credentials_file: /etc/prometheus/opencoder/token
  static_configs:
  - targets:
    - 127.0.0.1:18081
    labels:
      app: opencoder
