import assert from 'node:assert/strict';
import { chromium } from '../../../crates/web/spa/node_modules/playwright-core/index.mjs';

const [base, output] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || chromium.executablePath(), args: ['--no-sandbox', '--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport: { width: 1200, height: 850 } });
const failures = [];
page.on('pageerror', (error) => failures.push(error.message));
const dialog = page.locator('.ant-modal[role="dialog"]:visible');
const choose = async (scope, label, text, multiple = false) => {
  await scope.getByLabel(label, { exact: true }).click();
  const dropdown = page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden)');
  await dropdown.locator('.ant-select-item-option').getByText(text, { exact: true }).click();
  if (multiple) await scope.locator('.ant-modal-title').click();
  await dropdown.waitFor({ state: 'hidden' });
};
const submit = async () => {
  await dialog.getByRole('button', { name: /确\s*定/ }).click();
  await dialog.waitFor({ state: 'hidden' });
};
try {
  await page.goto(`${base}/?token=ontology-fixture`);
  const tabs = page.locator('.fleet-sidebar [role=tablist]');
  await tabs.getByRole('tab', { name: 'Ontology', exact: true }).click();
  await page.getByRole('heading', { name: '图谱', exact: true }).waitFor();
  const category = await tabs.evaluate((element) => ({ width: element.clientWidth, total: element.scrollWidth, left: element.scrollLeft,
    labels: [...element.children].map((tab) => ({ label: tab.textContent, overflow: tab.scrollWidth > tab.clientWidth, shrink: getComputedStyle(tab).flexShrink })) }));
  assert(category.total > category.width);
  assert(category.left > 0);
  assert(category.labels.every((tab) => !tab.overflow && tab.shrink === '0'));
  await page.getByRole('menuitem', { name: /实体类型$/ }).click();
  await page.getByRole('heading', { name: '实体类型', exact: true }).waitFor();
  await page.getByRole('button', { name: /新\s*增/ }).click();
  await dialog.getByLabel('类型 Key').fill('browser_type');
  await dialog.getByLabel('名称', { exact: true }).fill('浏览器类型');
  await dialog.getByRole('button', { name: /确\s*定/ }).click();
  await dialog.waitFor({ state: 'hidden' });
  await page.getByRole('cell', { name: '浏览器类型', exact: true }).waitFor();
  await page.getByRole('cell', { name: '浏览器类型', exact: true }).click();
  const drawer = page.locator('.ant-drawer-open');
  await drawer.getByRole('tab', { name: '属性', exact: true }).click();
  await drawer.getByRole('button', { name: /新增属性$/ }).click();
  await dialog.getByLabel('属性 Key').fill('owner');
  await dialog.getByLabel('名称', { exact: true }).fill('负责人');
  await choose(dialog, '类型', 'string');
  await submit();
  await drawer.getByRole('cell', { name: '负责人', exact: true }).waitFor();
  await drawer.getByRole('tab', { name: 'Action', exact: true }).click();
  await drawer.getByRole('button', { name: /新增 Action$/ }).click();
  await choose(dialog, '读写', '读');
  await dialog.getByLabel('操作', { exact: true }).fill('read_status');
  await submit();
  await drawer.getByText('read: read_status', { exact: true }).waitFor();
  await drawer.locator('.ant-drawer-close').click();
  await drawer.waitFor({ state: 'hidden' });
  await page.getByRole('menuitem', { name: /实体$/ }).click();
  await page.getByRole('heading', { name: '实体', exact: true }).waitFor();
  await page.getByRole('cell', { name: '入口服务', exact: true }).waitFor();
  await page.getByRole('button', { name: /新增实体$/ }).click();
  await choose(dialog, '实体类型', '浏览器类型');
  await dialog.getByLabel('名称', { exact: true }).fill('浏览器实体');
  await dialog.getByLabel('来源', { exact: true }).fill('# 浏览器来源');
  await dialog.getByLabel('扩展信息（Markdown）', { exact: true }).fill('# 浏览器扩展');
  await dialog.getByLabel('负责人', { exact: true }).fill('tester');
  await submit();
  await page.getByRole('cell', { name: '浏览器实体', exact: true }).waitFor();
  await page.getByRole('textbox', { name: '搜索实体' }).fill('入口');
  assert.equal(await page.getByRole('cell', { name: '下游服务', exact: true }).count(), 0);
  await page.getByRole('menuitem', { name: /关系类型$/ }).click();
  await page.getByRole('heading', { name: '关系类型', exact: true }).waitFor();
  await page.getByRole('button', { name: /新\s*增/, exact: true }).click();
  await dialog.getByLabel('类型 Key').fill('browser_relation');
  await dialog.getByLabel('名称', { exact: true }).fill('浏览器关系');
  await choose(dialog, '源实体类型', '服务');
  await choose(dialog, '允许目标类型', '服务', true);
  await submit();
  const relationRow = page.getByRole('row').filter({ has: page.getByRole('cell', { name: '浏览器关系', exact: true }) });
  await relationRow.getByRole('button', { name: '创建关系', exact: true }).click();
  await choose(dialog, '源实体', '入口服务');
  await choose(dialog, '目标实体', '下游服务');
  await submit();
  await page.getByRole('menuitem', { name: /图谱$/ }).click();
  const types = page.getByRole('combobox', { name: '实体类型多选' });
  await types.click();
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option').getByText('服务', { exact: true }).click();
  await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden)').getByRole('button', { name: /完\s*成/ }).click();
  await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden)').waitFor({ state: 'hidden' });
  await page.getByRole('checkbox', { name: '展开跨类型邻居' }).check();
  const centers = page.getByRole('combobox', { name: '实体多选' });
  await centers.click();
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option').getByText('入口服务', { exact: true }).click();
  await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden)').getByRole('button', { name: /完\s*成/ }).click();
  await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden)').waitFor({ state: 'hidden' });
  await page.locator('canvas:visible').first().waitFor();
  await page.getByRole('button', { name: '保存切面', exact: true }).click();
  await dialog.getByLabel('名称', { exact: true }).fill('浏览器切面');
  await dialog.getByRole('button', { name: /保\s*存/, exact: true }).click();
  await dialog.waitFor({ state: 'hidden' });
  await page.getByRole('tab', { name: '切面观测', exact: true }).click();
  await choose(page, '切面选择', '浏览器切面');
  await page.locator('canvas:visible').first().waitFor();
  await page.screenshot({ path: `${output}/desktop.png` });
  await page.getByRole('menuitem', { name: /环境管理$/ }).click();
  await page.getByRole('button', { name: /新增 ENV$/ }).click();
  await dialog.getByLabel('ENV Key').fill('browser_env');
  await dialog.getByLabel('名称', { exact: true }).fill('浏览器环境');
  await submit();
  await page.getByRole('cell', { name: '浏览器环境', exact: true }).waitFor();
  await choose(page, 'Ontology 环境', '浏览器环境');
  await page.getByRole('menuitem', { name: /实体类型$/ }).click();
  await page.getByRole('cell', { name: '目录', exact: true }).waitFor();
  assert.equal(await page.getByRole('cell', { name: '浏览器类型', exact: true }).count(), 0);
  await page.setViewportSize({ width: 240, height: 740 });
  const mobile = page.locator('.fleet-mobile-nav[role=tablist]');
  await mobile.getByRole('tab', { name: 'Ontology', exact: true }).click();
  await mobile.hover();
  await page.mouse.wheel(80, 0);
  await page.waitForFunction(() => document.querySelector('.fleet-mobile-nav[role=tablist]').scrollLeft > 0);
  const narrow = await mobile.evaluate((element) => ({ width: element.clientWidth, total: element.scrollWidth, left: element.scrollLeft,
    wrap: getComputedStyle(element).flexWrap, labels: [...element.children].map((tab) => tab.scrollWidth <= tab.clientWidth) }));
  assert(narrow.total > narrow.width && narrow.left > 0 && narrow.wrap === 'nowrap');
  assert(narrow.labels.every(Boolean));
  await page.screenshot({ path: `${output}/mobile.png` });
  assert.deepEqual(failures, []);
  console.log(JSON.stringify({ passed: true, pages: 5, attribute_action_config: true, entity_created: true,
    relationship_created: true, aspect_saved: true, environment_isolation: true, desktop: category, mobile: narrow }));
} catch (error) {
  await page.screenshot({ path: `${output}/browser-failure.png` });
  console.error(JSON.stringify({ error: error.message, failures }));
  throw error;
} finally { await browser.close(); }
